<?php

namespace AppBundle\Repository;

/**
 * EmailLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailLogRepository extends \Doctrine\ORM\EntityRepository
{
}
